#' adjust fitting function
#'
#' This is the function for adjusting model fitting.
#' @param bin_info_obj Required. Object of class binInfo, imported using method readBinInfo.
#' @param bin_count_obj Required. Object of class binCount, imported using method readBinCount.
#' @param sample_id Required. Sample name.
#' @param work_dir Working directory. Default is current directory.
#' @param proj_name Project name. Default is 'NA'.
#' @param min_n_x Minimum number of bins when grouping IP bins with the same Input bin count. Default is 50.
#' @param trunc_val Proportion of Input bins not taken as outliers. Default is 0.999.
#' @param k_down Minimum k. Default is 2.
#' @param k_up Maximum k. Default is 6.
#' @param mu_init Initiation value of signal mean. Default is 0.1.
#' @param var_init Initiation value of signal variance. Default is 0.15.
#' @param iter_stop Iteration times. Default is 100.
#' @param reg Regression method. Valid values are 'rlm' for RLM(robust fitting of linear models) and 'gam' for GAM(generalized additive models). 
#' @param fdr False discovery rate. Default is 0.05.
#' @param output_intmd If save intermediate output. Default is TRUE.

#' @export
#' @author Yiqian Zhang
#' @examples
#' #bin_info_*.tsv and bin_count_*.tsv are generated by the main function 'moaims' when setting output_intmd=T(default)
#' bin_info_obj=readBinInfo(in_fn = /absolute/path/to/bin_info_*.tsv)
#' bin_count_obj=readBinCount(in_fn = /absolute/path/to/bin_count_*.tsv)
#' adjFit(bin_info_obj,bin_count_obj,sample_id='test')


adjFit <- function(
  bin_info_obj=NULL,
  bin_count_obj=NULL,
  sample_id=NULL,
  work_dir='.',
  proj_name='NA',
  min_n_x=50,
  trunc_val=0.999,
  k_down=2,
  k_up=6,
  mu_init=0.1, 
  var_init=0.15,
  iter_stop=100,
  reg="rlm",
  fdr=0.05,
  output_intmd=TRUE
  ){
  
  #check working directory
  if(dir.exists(work_dir)){
  	setwd(work_dir)
  } else{
    stop( "Stop! Working directory not found." ) 
  }

  
  #check required parameters
  if ( is.null(bin_info_obj) ) { stop( "Stop! Bins info. is required. Get bins info. from file bin_info_* ." ) }
  if ( is.null(bin_count_obj) ) { stop( "Stop! Bin count is required. Get bin count from file bin_count_* ." ) }
  if ( is.null(sample_id) ) { stop( "Stop! Sample ID is required." ) }

    
  dir.create(proj_name) 
  setwd(proj_name)
  
  if(output_intmd==TRUE){
      dir.create("intermediate") 
  }
  
  
  fit_obj=NULL
  min_BIC=Inf
  optim_k=k_down
  
  for (k in k_down:k_up){
    
    	fit_obj_tmp=fitEM(bin_count_obj,
                  		  min_n_x=min_n_x,
                  		  trunc_val=trunc_val,
                  		  k=k,
                  		  reg=reg,
                  		  mu_init=mu_init, 
                  		  var_init=var_init,
                  		  iter_stop=iter_stop)
        if (fit_obj_tmp@val_BIC_2s<min_BIC){
        	fit_obj=fit_obj_tmp
        	min_BIC=fit_obj_tmp@val_BIC_2s
        	optim_k=k
        }
  }

  #plotGOF
  plotGOF(fit_obj=fit_obj,
          bin_count_obj=bin_count_obj,
          sample_id=sample_id,
          k=optim_k)

  
  if(fit_obj@val_BIC_1s<fit_obj@val_BIC_2s){
        #sig region 1S
	    sig_region_obj_1s=callSigRegion(bin_count_obj,fit_obj,fdr=fdr,mode="1S")
	    #output
		saveSigRegion(sig_region_obj_1s,bin_info_obj,sample_id)
		
		if(output_intmd==TRUE){
			saveSigBin(sig_region_obj_1s,bin_info_obj,sample_id)
		}
  
    } else{
        #sig region 2S
	    sig_region_obj_2s=callSigRegion(bin_count_obj,fit_obj,fdr=fdr,mode="2S")
	    #output 
	    saveSigRegion(sig_region_obj_2s,bin_info_obj,sample_id)
	    	    
	    if(output_intmd==TRUE){
			saveSigBin(sig_region_obj_2s,bin_info_obj,sample_id)
		}
    }
	

  fit_obj_all=NULL
  optim_k_all=NULL
  optim_reg_all=NULL
  
  fit_obj_all=c(fit_obj_all,fit_obj)
  optim_k_all=c(optim_k_all,optim_k)
  optim_reg_all=c(optim_reg_all,reg)

  saveFit(fit_obj_all=fit_obj_all,
		  optim_k_all=optim_k_all,
		  optim_reg_all=optim_reg_all,
		  proj_name=sample_id,
		  sample_id_all=sample_id)

}

