#' import object of class binCount.
#'
#' This is the function for importing object of class binCount.
#' @param in_fn Required. Input file bin_count_*, generated by the main function of moaims when setting output_intmd=T(default).

#' @export
#' @author Yiqian Zhang
#' @examples
#' bin_count_obj=readBinCount(in_fn = /absolute/path/to/bin_count_*.tsv)


readBinCount <- function(in_fn=NULL){
  
  #check required parameters
  if ( is.null(in_fn) ) { stop( "File bin_count_* is required!" ) }

  df=read.delim(in_fn,header=F,sep="\t")
  df[,1]=as.character(df[,1])
  
  bin_count_obj <- new( "binCount", 
                       bin_id=df[,1],
                       ip=df[,2],
                       input=df[,3]) 
  
  return(bin_count_obj)
  
}



